### ISSUE TITLE
Support for the Microsoft Store version

### ISSUE THREAD

**Issue by netthier** [robertnunn/DRG-Save-Editor#11]
If DRG is installed using the Microsoft Store instead of Steam, the editor crashes with the following error:
![](https://media.discordapp.net/attachments/172645867570987008/834485059326705714/Capture.PNG)

The code currently assumes Steam is installed, and crashes if it isn't.

**Comment by robertnunn** [comment]
Just updated, editor shouldn't crash anymore. Please let me know if this fixes your issue.

**Comment by netthier** [comment]
Awesome, the issue is now fixed. Thank you very much for your quick reply and fix!
