### ISSUE TITLE
Suggestion: Add option to clear Sandbox status on saves. 

### ISSUE THREAD

**Issue by Kolkonut** [robertnunn/DRG-Save-Editor#15]
It would be useful to be able to remove the Sandbox status placed on saves that have used certain types of mods.

**Comment by Kolkonut** [comment]
I've looked at the files, and there is a string of field that is labelled "isModded", seeming to be under the "BoolProperty" category. I suspect you would have to change that.

**Comment by robertnunn** [comment]
I'll take a look, but it's not a priority right now.

**Comment by rhulha** [comment]
Hey Robert,

A friend of mine had the flares mod installed and silently was put into sandbox mode.
Now she got the Halloween gear but only in her sandbox save game.
I would pay you if you add support for this.

Please contact me for details.

**Comment by robertnunn** [comment]
I have no plans at the moment to add support for the modded flag, but you can change it yourself by changing the "isModded" flag to 0, then renaming the "modded" save to the name of the original, unmodded save. See the attached image for exactly where this flag is. You'll need a hex editor to make the change
![modded flag](https://user-images.githubusercontent.com/38513230/142232502-160582fb-ba87-46d1-a009-ff9d08505bbc.png)
s.

**Comment by rhulha** [comment]
Thank you
