### ISSUE TITLE
Version 1.4 doesn't show new overclocks

### ISSUE THREAD

**Issue by Graveryl** [robertnunn/DRG-Save-Editor#19]
Hi,

I've just downloaded the latest version (1.4) in hope of unlocking the new overclocks for the new weapons but the editor doesn't show them. It looks like the old editor instead of the updated one showed in the screenshots. Any thoughts as to why?

**Comment by Graveryl** [comment]
Amazing program by the way, thanks for your work on this.

**Comment by MDC-Dashie** [comment]
G'day mate. 

Just want to add on the same issue, downloaded and checked it, when I opened it up, none of the new weapons showed up in the editor. Hope this gets resolved, cheers mate.

**Comment by JeSuisRevenir** [comment]
Just adding on here to say that I'm having the same issue with the new weapons not showing up in the GUI

**Comment by pyradyne** [comment]
Same issue here, vary good program however, keep up the work, Thanks!

**Comment by robertnunn** [comment]
Apparently things got a little mixed up when I was building/packaging the editor and the guids.json didn't get updated properly. It should be fixed now.

**Comment by Graveryl** [comment]
Confirmed to be working. Thank you so much!
