### ISSUE TITLE
UI now loads but hangs and freezes when loading save file

### ISSUE THREAD

**Issue by naeem-bvg** [robertnunn/DRG-Save-Editor#2]
Replicated many times. Have left it hanging for 5+ minutes in case it was a load time thing.

Steps:
- Launch with .cmd
- Load save file from DRG dir
- Get spinner
- Grayed out UI
- Spinner for life

**Comment by naeem-bvg** [comment]
Left it while playing. Did eventually load but cannot say when it completed. Is this expected behaviour?

**Comment by robertnunn** [comment]
If you haven't updated to the latest version (v1.3.2, which was only uploaded about 3 hours ago) please do so. This fixes a similar problem. If that doesn't fix it, there is a known bug where the editor freezes like you described when you haven't forged any overclocks (any kind, not just weapon). If neither of these fixes the problem, please upload your save file and I'll take a look.

**Comment by naeem-bvg** [comment]
It must be the latter. I am a new player and can't say I know what an overlock is. I am on 1.3.2 as previous was not even loading UI. Cheers for the reply.

**Comment by robertnunn** [comment]
Ah, then it's likely you'd just need to forge an overclock. [The wiki](https://deeprockgalactic.gamepedia.com/Deep_Rock_Galactic_Wiki) has a lot of good information about the game, including details on overclocks. The bugfix for this is coming in the next patch, which should be in the next day or two.

**Comment by robertnunn** [comment]
I just pushed the next version, which should address your issue.

**Comment by naeem-bvg** [comment]
Works well thanks
