### ISSUE TITLE
After opening a save file, editor stops responding

### ISSUE THREAD

**Issue by elishmidt** [robertnunn/DRG-Save-Editor#20]
After importing save file, editor just crashes and stops responding. I can't attach a .sav file. Instead I've changed the extension to .log and have also uploaded it to puush.

https://puu.sh/IpNFn/b6cfadcee8.sa

[76561198315523025_player100p.sav.log](https://github.com/robertnunn/DRG-Save-Editor/files/7557056/76561198315523025_player100p.sav.log)
v

**Comment by robertnunn** [comment]
Just updated, please let me know if it's still hanging after updating.
