### ISSUE TITLE
Support for Missions Statistics

### ISSUE THREAD

**Issue by Larax1011** [robertnunn/DRG-Save-Editor#22]
Amazing program you got here! I couldn't imagine how long it took you trying to find everything in HxD.

Wanted to see if you maybe dabbled in editing the missions statistics for each of the classes?
IE Completed missions, <Mission type> Completed, etc. 

I've dug around with HxD and saw that there's some MissionStatID values that are linked with some GUIDs which look similar to the ones you use for your class markers.

**Comment by robertnunn** [comment]
Sorry, I have no intention of adding the ability to edit those values. You're free to submit a pull request if you want to add it yourself, but it wouldn't be a priority for me.
