### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by stparcher** [robertnunn/DRG-Save-Editor#25]
after modifying the save file I can't get it to reflect my changes in the game. 
Here is the file
[76561198140597194_Player_ExternalBackup_0.txt](https://github.com/robertnunn/DRG-Save-Editor/files/7662800/76561198140597194_Player_ExternalBackup_0.txt)

**Comment by stparcher** [comment]
i cant get it to work it a good program tho

**Comment by robertnunn** [comment]
Without even downloading the file I think I see the problem. This is (probably) the backup of your save that DRG makes. You'll want to open/edit the file named "76561198140597194_Player.sav". Does that fix the problem?

**Comment by stparcher** [comment]
I did edit the player file that's the one I was supposed to I just couldn't get it to change it to the txt file, but here it is
[76561198140597194_Player.txt](https://github.com/robertnunn/DRG-Save-Editor/files/7671841/76561198140597194_Player.txt)

**Comment by stparcher** [comment]
could it be that what I changed was too much for the game to register

**Comment by robertnunn** [comment]
The problem here is that several of the fields that the editor is trying to change aren't present in your save (likely because you just haven't gotten there yet). This is a known issue and the solution is to acquire at least one of those resources in game and _then_ use the editor.

**Comment by stparcher** [comment]
thats weird because i have at least one of each brewing ingredient yet I can't change how many I have of them

or is this more about the overcharges, and levels?
