### ISSUE TITLE
Adding error cubes and blank cores isnt working.

### ISSUE THREAD

**Issue by ProfessorMoriarty123** [robertnunn/DRG-Save-Editor#26]
When i join to forge, it says i have no blank cores. Then when i open that same save again with the editor a second time, it says that there are billions of them in it. Adding overclock parts isnt working either.

**Comment by robertnunn** [comment]
Is this a fresh save or one that you've been playing on for a while? It's a known issue that if those fields aren't present in your save (mostly because you haven't done that on that save yet) the editor has trouble with that.
