### ISSUE TITLE
UI Render - Label overflow and elements are overlapping

### ISSUE THREAD

**Issue by naeem-bvg** [robertnunn/DRG-Save-Editor#3]
Label overflow and elements are overlapping.

<img width="1108" alt="Screenshot_12" src="https://user-images.githubusercontent.com/17141136/103596334-96ddbb80-4ef5-11eb-92c1-0b33ba7c3ea6.png">
<img width="622" alt="Screenshot_11" src="https://user-images.githubusercontent.com/17141136/103596337-97765200-4ef5-11eb-9d4a-c86b8466a0bd.png">

**Comment by robertnunn** [comment]
Have you changed your system font settings at all? This is the first time out of four people I've seen this error.

**Comment by naeem-bvg** [comment]
Not the font settings, but that did clue me in to something. I am on a 4k monitor running 150% scaling. Changing to 100% will resolve. Personally I'll manage with this rather than constantly changing my desktop settings.

As an aside, the error cubes and blank core counts are incorrect (0,0). Perhaps this is due to the problem you mention in the other thread for users who haven't done an OC.

**Comment by robertnunn** [comment]
Yes it's likely related to the overclock bug, I would not recommend using the editor until this bug is fixed since it could corrupt your save. If you're dead set on editing your save, there is a text document that details how to make some changes manually.
