### ISSUE TITLE
Lost the drillers sludge pump

### ISSUE THREAD

**Issue by repcsi** [robertnunn/DRG-Save-Editor#30]
Hello Guys,

Sometime after the last update I lost the drillers sludge pump due to a cloud savegame restoration, or some other issue. I never used drg editor before. Do you have an idea how I could readd the sludge pump? I lost the pump and I don't have the assignment to unlock it.

**Comment by robertnunn** [comment]
Sorry, the editor doesn't support adding weapons in that way.

**Comment by repcsi** [comment]
Yeah I know, I checked it, but found no info on the weapon id-s. Thx anyway will try the GSG bugreporting jira
