### ISSUE TITLE
Current Version does not detect new season content

### ISSUE THREAD

**Issue by kagrith** [robertnunn/DRG-Save-Editor#35]
I imagine this has to do with GUIDs needing to be updated?
I was curious if perhaps some of the data for the new season would be stored in the same way as the old season, but editor does not seem to be able to find the new values.

A new resource was added as well.

Not sure if you intend to update for this season, but perhaps making season content a collapsible segment that contains each season's content, similar to overclocks.

I imagine such an accordian style system could also be used for cosmetic overclocks, seeing as how most of them have known guids, similar to woesbot's merge request from last year.
External guid tables broken up by category might make it easier for the community to contribute.

**Comment by TheTrueGraveDigger** [comment]
don't think it's ever gonna get updated, it seems to look like the idea has been abandonded

**Comment by EKSZeroPercent** [comment]
That's too bad, I really enjoyed this tool.

**Comment by robertnunn** [comment]
Updated for season 2, but adding OCs is broken due to changes in save file format. Please see the readme.

**Comment by EKSZeroPercent** [comment]
I have a save file with all cosmetics (that don’t come from crates) and all new OCs if you need it or it could help in anyway.

I use the editor for resources (especially scrip).

thank you for the tool, it’s incredible!

**Comment by robertnunn** [comment]
If the save has 3+ unforged overclocks, that would be helpful. A save with the OCs already forged is not super useful since I already have that kind of data.

**Comment by EKSZeroPercent** [comment]
Ah, sorry. Unfortunately mine are all forged. I used the beta client to create a save with all forged new OCs before the patch dropped. When I’m home I’ll see if I can still access the unforced OC saves or if I know someone that has some.

**Comment by kagrith** [comment]
[76561198007037004_Player (2).zip](https://github.com/robertnunn/DRG-Save-Editor/files/8598099/76561198007037004_Player.2.zip)


> If the save has 3+ unforged overclocks, that would be helpful. A save with the OCs already forged is not super useful since I already have that kind of data.


Here is a zip file with a playerfile with five unforged overclocks, i think i have one for each weapon, might be only 3 of the 4 new weapons, one is definitely a cosmetic.
When loaded into the new editor, it does identify the coilgun properly, but my other overlocks are identified as cosmetics.
