### ISSUE TITLE
perk points no longer being changed and insanely high number

### ISSUE THREAD

**Issue by themercesletifer** [robertnunn/DRG-Save-Editor#7]
![drgsg](https://user-images.githubusercontent.com/80370621/110563301-39891380-819f-11eb-80e7-988fa248d9d6.png)
i was able to change perk points just fine before, and now recently anytime I load my save up the perk points are showing an insane number when I never set it to be that and i can no longer change them

**Comment by robertnunn** [comment]
I just tested this on my end and perk points were read and changed successfully. Can you please attach your save file so I can compare?

**Comment by themercesletifer** [comment]
[Perk Points Bugged Save.zip](https://github.com/robertnunn/DRG-Save-Editor/files/6112600/Perk.Points.Bugged.Save.zip)

**Comment by themercesletifer** [comment]
I also tried to set it to zero, save it, get in game, then test and see if it is still bugged and it is. Set to zero > loaded save fine, zero points in game. Opened in the editor afterwards, instantly set to same number

**Comment by robertnunn** [comment]
When I compare our saves in a hex editor, I don't see the marker that the editor uses to find the entry for perk points, that's why it's not working. I'm still investigating a fix, but I would speculate that if you got even a single perk point in the game, you should be able to edit them from there.

**Comment by themercesletifer** [comment]
I will test it out and let you know

**Comment by themercesletifer** [comment]
Can confirm earning atleast a single perk point re enables the marker for the editor so that it correctly works.

**Comment by robertnunn** [comment]
Glad to hear. I have an idea for a fix, and should have it pushed out by the end of the day tomorrow (at the latest).
