### ISSUE TITLE
Save editor not reading existing rank / promotion of characters, cannot edit beyond Legendary 3 Promotion

### ISSUE THREAD

**Issue by alientknight** [robertnunn/DRG-Save-Editor#8]
At the moment it appears that ranks are automatically generated based on level + promotion rank, but no matter the rank that's in the save file, the editor will read them as 'blank', which is a negative value.

And for any class that has promoted beyond Legendary 3 there won't be a way to obtain Legendary 3+ or ++++ depending on how many promotions are done beyond Legendary 3, resulting in lost ranks from a save that has 1400+ ranks.

**Comment by robertnunn** [comment]
Can you please attach your save file (from before editing) so I can see what the error is?

**Comment by alientknight** [comment]
Here it is!
[76561198064718597_Player.zip](https://github.com/robertnunn/DRG-Save-Editor/files/6166426/76561198064718597_Player.zip)

**Comment by robertnunn** [comment]
I've updated the editor and it should preserve your levels if the promotion drop-down is left on "Legendary 3+". Please let me know if it works.

**Comment by alientknight** [comment]
Works perfectly on my end, amazing job!

**Comment by robertnunn** [comment]
Glad to hear.
